name: Rule Conversion
on: 
  workflow_dispatch:
  schedule:
  - cron: 0 */12 * * *

env:
  TZ: Asia/Shanghai
  MIHOMO_VERSION: 1.19.10
  RULES_DOWNLOAD_FILE: urls.yaml

jobs:
  Rule_Conversion:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget gzip
          sudo timedatectl set-timezone "$TZ"
      
      - name: Download Mihomo
        run: |
          wget -c -O mihomo-linux-amd64-v${{env.MIHOMO_VERSION}}.gz https://github.com/MetaCubeX/mihomo/releases/download/v${{env.MIHOMO_VERSION}}/mihomo-linux-amd64-v${{env.MIHOMO_VERSION}}.gz
          gzip -df mihomo-linux-amd64-v${{env.MIHOMO_VERSION}}.gz
          chmod +x mihomo-linux-amd64-v${{env.MIHOMO_VERSION}}

      - name: Download Yq
        run: |
          wget -c -O yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x yq

      - name: Convert Rules
        run: |
          chmod +x main.sh
          export MIHOMO_VERSION=${{env.MIHOMO_VERSION}}
          export RULES_DOWNLOAD_FILE=${{env.RULES_DOWNLOAD_FILE}}
          ./main.sh
          rm -rf mihomo-linux-amd64-v${{env.MIHOMO_VERSION}}*
          rm -fr yq
      
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto update"
          file_pattern: "./rules/*"
          branch: release
          disable_globbing: true
