name: Rule Conversion
on: 
  workflow_dispatch:
  schedule:
  - cron: 0 */12 * * *

env:
  TZ: Asia/Shanghai
  MIHOMO_VERSION: 1.19.10

jobs:
  Rule_Conversion:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl gzip
          sudo timedatectl set-timezone "$TZ"
          mkdir -p rules

      - name: Download Rules
        id: update
        run: |
          curl -O --output-dir ./rules https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
          curl -O --output-dir ./rules https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
      
      - name: Format Conversion
        run: |
          wget https://github.com/MetaCubeX/mihomo/releases/download/v${{env.MIHOMO_VERSION}}/mihomo-linux-amd64-v${{env.MIHOMO_VERSION}}.gz
          gzip -d mihomo-linux-amd64-v${{env.MIHOMO_VERSION}}.gz
          chmod +x mihomo-linux-amd64-v${{env.MIHOMO_VERSION}}
          ./mihomo-linux-amd64-v${{env.MIHOMO_VERSION}} convert-ruleset domain yaml ./rules/direct.txt ./rules/direct.mrs
          ./mihomo-linux-amd64-v${{env.MIHOMO_VERSION}} convert-ruleset domain yaml ./rules/gfw.txt ./rules/gfw.mrs
          rm -rf mihomo*
          rm -fr ./rules/*.txt
      
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto update"
